#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
	yt='yt-dlp -o "%(uploader)s-%(title)s.%(ext)s" -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4" --add-metadata -icv' \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="eza --color=auto --group-directories-first --icons=auto" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

#ls="ls -hN --color=auto --group-directories-first"
# These common commands are just too long! Abbreviate them.
alias \
	update="~/dev/scripts/upgrade_with_snapshot.sh" \
	ka="killall" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	shred="shred -zuvn 5" \
	..='cd ..' \
	...='cd ../..'

# git shortcuts
alias \
	g="git" \
	ga="git add" \
	gcm="git commit -am" \
	gp="git push origin main" \
	gstat="git status" \
	gc="git clone"
